completed POM homework
RUSTEMATOR/Playwright_training pull request #3
Opened 2024-07-31 18:19 UTC by RUSTEMATOR

2024-07-31 20:02 UTC, sttaran requested changes

2024-07-31 20:02 UTC, sttaran commented on tests/first.spec.js
> +      RegPopUp = await welcomePage.header.clickRegButton();
RegPopUp is an insyance, it should be caalled `regPopUp`

2024-07-31 20:02 UTC, sttaran commented on tests/first.spec.js
> +        await expect(RegPopUp.regPopUpModal).toBeVisible();
what is RegPopUp.regPopUpModal?

2024-07-31 20:02 UTC, sttaran commented on tests/first.spec.js
> +      await RegPopUp.fillIn({email: 'rako@roflan.com'})
save email to a variable and reuse it

2024-07-31 20:02 UTC, sttaran commented on tests/first.spec.js
> +      await RegPopUp.fillIn({email: 'rako@roflan.com'})
same for other tests

2024-07-31 20:02 UTC, sttaran commented on src/pageObjects/BasePage.js
> +    constructor(page, url, WaitPageLocator){
WaitPageLocator is an instance of Locator

should be `waitPageLocator`

2024-07-31 20:02 UTC, sttaran commented on src/pageObjects/welcomePage/WelcomePage.js
> +        this.signInButtonText = page.locator('Sign In')
why?

wrong selector and strange name + this is unused

2024-07-31 20:02 UTC, sttaran commented on src/pageObjects/welcomePage/WelcomePage.js
> +        this.signUpButton = page.locator('.hero-descriptor_btn.btn.btn-primary')
`.hero-descriptor_btn` would be enough

2024-07-31 20:02 UTC, sttaran commented on src/pageObjects/welcomePage/components/RegPopUp.js
> +        this._passDontMatchErr = page.locator('div.invalid-feedback > p').filter({hasText: 'Passwords do not match'})
don't make locators per text

it is the same element but with different content

2024-07-31 20:02 UTC, sttaran commented on src/pageObjects/garagePage/GaragePage.js
> +export default class GaragePage extends BaseComponent {
`export default class GaragePage extends BasePage`

2024-08-01 08:34 UTC, RUSTEMATOR commented on tests/first.spec.js
> +        await expect(RegPopUp.regPopUpModal).toBeVisible();
<img width="1439" alt="Screenshot at Aug 01 11-34-18" src="https://github.com/user-attachments/assets/c7ef2d80-c475-4ae6-9914-4ef7050b68eb">

The pop-up itself: <app-signup-modal _nghost-ysg-c48="">

Is there any way to name this element better or this step is to be omitted at all?

2024-08-01 09:01 UTC, RUSTEMATOR commented on src/pageObjects/welcomePage/WelcomePage.js
> +        this.signInButtonText = page.locator('Sign In')
Don't even remember why I did that. Probably was half asleep

2024-08-01 16:19 UTC, closed without merging